### ISSUE TITLE
Vue Syntax Highlight 3.2.5 does not work in Siblime 3157

### ISSUE THREAD

**Issue by titovmaxim** [vuejs/vue-syntax-highlight#128]
Installed the latest Sublime 3157, use Package control to install Vue Syntax Highlight 3.2.5. As a result .vue files are almost not highlighted.

The example is shown in the screenshot attached.

<img width="580" alt="2018-02-17 15 11 23" src="https://user-images.githubusercontent.com/1524918/36339303-dd2ea76e-13f4-11e8-88d6-b55942b4406a.png">

**Comment by skyronic** [comment]
Does this issue also happen when the `template` tag is above the `<script>`?

**Comment by titovmaxim** [comment]
yes, does not matter

**Comment by JGJP** [comment]
Adding a semicolon after the last closing bracket (line 9 in @titovmaxim's example) solves this problem for now, I'd rather not have to add this to all my files though.

**Comment by skyronic** [comment]
I can't seem to reproduce this

![image](https://user-images.githubusercontent.com/80173/39736481-25c0e720-524e-11e8-8cba-a5ab60d2919e.png)

However, this seems to be because of the way sublime works, and the way the JavaScript standard has been implemented. You can see a reply by a dev who works on the Sublime JS sytnax here - https://github.com/vuejs/vue-syntax-highlight/issues/107#issuecomment-344721940

Essentially the `;` is required at the end of an `export` statement even though most people don't use it. If it isn't placed, the export statement doesn't "end", and this messes up the interpreter. 

I personally use the Babel sublime package, and I find that it works much better for vue's JS code \, you have to install Babel extension and disable the builtin JS extension.

**Comment by skyronic** [comment]
This has been fixed and new version will be released soon.

**Comment by Reeseman** [comment]
<img width="657" alt="Screen Shot 2021-09-26 at 5 30 20 PM" src="https://user-images.githubusercontent.com/6230189/134829850-7e291e2f-f3cb-41d2-9696-762b62d2f2df.png">

Not fixed

**Comment by skyronic** [comment]
@Reeseman what version of sublime is this?
